# This workflow will buil the .NET code and run the tests on every pull request to the dev branch

name: Test

on:
  push:
    branches: [ "dev" ]

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
